### ISSUE TITLE
Basic checks

### ISSUE THREAD

**Issue by 7Ragnarok7** [7Ragnarok7/Dot.Chat#1]
- [x] Make sure all images have alt attribute.

- [x] Add icons to the titles.

- [x] Close all the inline css and externall css properly.

- [x] Add appropriate title attributes to the tags if you think it is required.

- [x] Make comments above each css section.

- [x] Make a database user named "dummy" and password "1234".

@subhrapatra @BlazinGirl Assign yourself to this issue and keep updating this list as you keep completing the above tasks.

**Comment by BlazinGirl** [comment]
Sure...
On it.

Liza Rozario,
Student of Department of Computational Sciences,
Brainware University, Barasat
Contact no. 9674198438,
Email address: liza.rozario0809@gmail.com.

**Comment by BlazinGirl** [comment]
2 Tasks done.

**Comment by BlazinGirl** [comment]
all the issues resolved except the last one.

**Comment by 7Ragnarok7** [comment]
👍🏻
